### ISSUE TITLE
Image Caching is not working.

### ISSUE THREAD

**Issue by Haibo-Zhou** [V8tr/AsyncImage#2]
Hello, I run this app on iPhone, it seems that image caching is not worked, as I see that if I force-close the app and reopen it, then images were reloading but not fetch from cache.

**Comment by V8tr** [comment]
Hi! Yep, that is by design. Image cache is not persisted between app launches. [This article](https://www.swiftbysundell.com/articles/caching-in-swift/) seems like a good solution on how to build a disk cache on top of `NSCache`.
