### ISSUE TITLE
Cannot convert value of type 'Image' to expected argument type '_?'

### ISSUE THREAD

**Issue by podiyaaa** [V8tr/AsyncImage#3]
Hi @V8tr 

i was going to run your async image project and got following error.

<img width="953" alt="Screenshot 2020-04-12 at 8 48 17 AM" src="https://user-images.githubusercontent.com/9278751/79059683-8bc56a00-7c9a-11ea-88ea-81751514ae61.png">

**Comment by dlepke** [comment]
I also came across this issue. It seems to go away once I comment out the environment variable line, but I need that!

**Comment by V8tr** [comment]
The latest update fixes the issue. Thanks for posting it here!
