### ISSUE TITLE
Load black images and first load not show images

### ISSUE THREAD

**Issue by luisrmz92** [V8tr/AsyncImage#4]
load images black
![image](https://user-images.githubusercontent.com/66233420/84261183-f2230900-aae0-11ea-922d-57997dd3589a.png)

first load
![image](https://user-images.githubusercontent.com/66233420/84261318-2f879680-aae1-11ea-8839-c9c78f4d932d.png)

second load
![image](https://user-images.githubusercontent.com/66233420/84261339-38786800-aae1-11ea-895f-6d2b206bc637.png)

**Comment by ghost** [comment]
The Author should consider put the following modifier in method private var image: some View: .renderingMode(.original)
The whole method would then this:
private var image: some View {
        Group {
            if loader.image != nil {
                Image(uiImage: loader.image!)
                    .resizable().renderingMode(.original)
            } else {
                placeholder
            }
        }
    }

This solved the black image phenomenon when using AsyncImage() i.e. in a SwiftUI-Button-View

**Comment by filimo** [comment]
@NeoLeonGithub Thanks for solution
 `.renderingMode(.original)` helps me without `.resizable()`
The problems came when I started using AsyncImage into Button inside of List on iOS 13. iOS 14 works fine without it.

**Comment by V8tr** [comment]
@NeoLeonGithub thanks for suggesting the solution! I am closing the issue since the problem has been addressed.
