### ISSUE TITLE
macOS Catalyst Support?

### ISSUE THREAD

**Issue by RichardHyde** [V8tr/AsyncImage#5]
Hi,

Thanks for the code. Whilst Ive got this working ok on iOS, when I try and run my app as a Catalyst app the "Loading…." placeholder is never replaced.

Has anyone had any luck running this as a Catalyst app or is it just me?

From what I can tell the image is being downloaded ok, but it doesn't seem to trigger the update to the AsyncImage view in the .assign

My first thought is that is a combine/SwiftUI issue under rather than anything to do with the AsyncImage code.

Cheers,

Richard

**Comment by lukemorse** [comment]
Hey, did you find a workaround?  The placeholder is replaced for me, but when I change state variables on the parent view, it causes the AsyncImage to reload, and sometimes it goes back to the placeholder.

**Comment by RichardHyde** [comment]
Hi, No I haven't yet. I was hoping Xcode 11.6 would solve it but it's still happening.
