### ISSUE TITLE
I cloned your project and not compile

### ISSUE THREAD

**Issue by JosepEscobar** [V8tr/AsyncImage#9]
I have this errors: 

`/Users/josepescobar/Downloads/AsyncImage-master/AsyncImage/ContentView.swift:26:30: Cannot convert value of type 'Text' to expected argument type '_?'`

`/Users/josepescobar/Downloads/AsyncImage-master/AsyncImage/ContentView.swift:22:10: Cannot convert return expression of type 'List<Never, ForEach<[URL], URL, HStack<some View>>>' to return type 'some View'`

**Comment by AbePlays** [comment]
Stuck here too :(

**Comment by V8tr** [comment]
Hi! Just updated the project for iOS 14. Must compile now!
